services:
  db:
    image: postgres:17
    container_name: vera-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vera
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d vera"]
      interval: 10s
      timeout: 5s
      retries: 5

  identity:
    build: ./vera-identity-service
    container_name: vera-identity
    ports:
      - 8081:8080
    environment:
      - BASE_URL=http://localhost:8081
      - DATABASE_URL=postgres://user:pass@db:5432/vera?sslmode=disable
      - SITE_URL=http://localhost:8080
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ACCESS_TOKEN_TTL=5m
      - ACCESS_TOKEN_SECRET=only-for-test
      - REFRESH_TOKEN_TTL=30m
      - REFRESH_TOKEN_SECRET=only-for-test
    depends_on:
      - db

  drive:
    build: ./vera-drive-service
    container_name: vera-drive
    ports:
      - 8082:8080
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/vera?sslmode=disable
      - IDENTITY_SERVICE_URL=http://identity:8080
      - SITE_URL=http://localhost:8080
    depends_on:
      - db

  site:
    build:
      context: ./vera-site
      args:
        - NEXT_PUBLIC_IDENTITY_SERVICE_URL=http://localhost:8081
        - NEXT_PUBLIC_DRIVE_SERVICE_URL=http://localhost:8082
    container_name: vera-site
    ports:
      - 8080:80
